### ISSUE TITLE
v0.6.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#105]
Issues:

- implement #7 
- add #25 
- implement #27 
- add #60 
- add #66 
- add #68 
- add #70 
- implement #71 
- test and document #79 
- implement #80 
- implement #81 
- fix #82 
- add #83 
- add #84, chain pipelines
- implement #85 
- implement #86, upstream as https://github.com/huggingface/diffusers/pull/2158
- implement #88 
- implement #96 
- fix #99 
- fix #100 
- fix #101 
- fix #106 
- fix #108 
- fix #109 
- fix #110 
- add #111
- fix #112 

Merges:

- #91 
- #92 
- #93 
- #94 
- #102

Testing:

- txt2img
  - 256x256 with SD v1.5
    - [x] should fail: neon blobs
    - [x] seems to work (sometimes?) with DPM multi
    - [x] attempt 2
  - 512x512 with SD v1.5
    - DPM Multi
      - [x] should work
      - [x] attempt 2
    - Euler A
      - [x] should work
      - [x] attempt 2
  - 512x512 with SD v2.1
    - [x] should work
    - [x] attempt 2
  - 768x768 with SD v2.1
    - [x] should work, given sufficient memory
    - [x] attempt 2
  - extra models
    - 512x512 with Knollingcase
      - [x] should work
      - [x] attempt 2
    - 512x512 with OpenJourney
      - [x] should work
      - [x] 256x256 seems to work as well
      - [x] attempt 2
- img2img
  - 256x256 input
    - [x] should fail: neon blobs
    - [x] attempt 2
  - 512x512 input
    - [x] should work
    - [x] attempt 2
  - 1024x768 input
    - [x] should work
    - [x] attempt 2
- inpaint
  - outpaint
    - 0 all sides
      - [x] should work, run 1 tile
      - [x] attempt 2
    - 256 all sides
      - [x] should work, run 8 tiles: image came out ok, but card reported `Size: 1536x1536`
      - [x] attempt 2
    - 512 top and bottom, 0 left and right
      - [x] should work, run 3 tiles
      - [x] attempt 2
    - 512 left and right, 0 top and bottom
      - [x] should work, run 3 tiles
      - [x] attempt 2
- upscale
  - Real ESRGAN
    - with CodeFormer
      - [x] should work
      - [x] attempt 2
    - with GFPGAN
      - ~should work~ failed: scattered tiles, https://github.com/ssube/onnx-web/issues/108
      - [x] attempt 2
    - without face correction
      - [x] should work
      - [x] attempt 2
    - using x2 model and x4 scale
      - ~should fail: tiles~ worked: seems to have ignored scale and run at x2, reported size is correct
      - [x] attempt 2
    - using x4 model and x2 scale
      - ~should fail: tiles~ worked: seems to have ignored scale and run at x4
      - [x] attempt 2
    - using v3 model and x2 scale
      - ~should work~ failed: neon overlay, https://github.com/ssube/onnx-web/issues/109
      - [x] attempt 2
    - using v3 model and x4 scale
      - ~should work~ failed: neon overlay, https://github.com/ssube/onnx-web/issues/109
      - [x] attempt 2
  - Stable Diffusion
    - using x2 scale
      - [x] should fail: tiles
      - [x] attempt 2
    - using x4 scale
      - [x] should work
      - [x] attempt 2
    - with CodeFormer
      - ~should work~ failed: scattered tiles, https://github.com/ssube/onnx-web/issues/110
      - [x] attempt 2
    - with GFPGAN
      - [x] should fail: https://github.com/ssube/onnx-web/issues/87
      - [x] attempt 2
    - without face correction
      - [x] should work
      - [x] attempt 2
- interactions
  - generate a new image
    - [x] should request and then load an image from the server
  - delete a pending image
    - [x] should remove a single image and leave the rest
  - delete a finished image
    - [x] should remove a single image and leave the rest
  - copy an image to img2img
    - [x] should switch to the img2img tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to inpaint
    - [x] should switch to the inpaint tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - persist on refresh
    - [x] loading images
    - [x] switching tabs

Release:

- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make v0.6.0
- ~make sure packages and images have been built~ 
- [x] fix lint error (line length) from recent patches
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make v0.6.1
- [x] make sure packages and images have been built
- [x] update GH pages bundle and default version
- [x] post release on GH
- [x] make follow up tickets
- [x] close milestone and checklist

**Comment by ssube** [comment]
Real ESRGAN + GFPGAN failed with:

```
[2023-02-05 23:33:39,374] WARNING: onnx_web.device_pool: job txt2img_902278279_b2f2069fbb92453a47865671c194efa56bd10c955f3d264dc3a72de692bfcd5d_1675661585.png failed with an error: ['Traceback (most
 recent call last):\n', '  File "C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\device_pool.py", line 192, in job_done\n    f.result()\n', '  File "C:\\Users\\ssube\\AppData\\Local
\\Programs\\Python\\Python310\\lib\\concurrent\\futures\\_base.py", line 451, in result\n    return self.__get_result()\n', '  File "C:\\Users\\ssube\\AppData\\Local\\Programs\\Python\\Python310\\li
b\\concurrent\\futures\\_base.py", line 403, in __get_result\n    raise self._exception\n', '  File "C:\\Users\\ssube\\AppData\\Local\\Programs\\Python\\Python310\\lib\\concurrent\\futures\\thread.p
y", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n', '  File "C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\diffusion\\run.py", line 67, in run_txt2img_pipelin
e\n    image = run_upscale_correction(\n', '  File "C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\upscale.py", line 56, in run_upscale_correction\n    return chain(job, server, pa
rams, image, prompt=params.prompt, upscale=upscale)\n', '  File "C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\chain\\base.py", line 103, in __call__\n    image = process_tile_gri
d(\n', '  File "C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\chain\\utils.py", line 36, in process_tile_grid\n    tile_image = filter(tile_image, (left, top, tile))\n', '  File "
C:\\Users\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\chain\\base.py", line 96, in stage_tile\n    tile = stage_pipe(job, server, stage_params, params, tile, **kwargs)\n', '  File "C:\\Us
ers\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\chain\\correct_gfpgan.py", line 72, in correct_gfpgan\n    gfpgan = load_gfpgan(server, upscale, upsampler=upsampler)\n', '  File "C:\\User
s\\ssube\\stabdiff\\onnx-try-2\\onnx-web\\api\\onnx_web\\chain\\correct_gfpgan.py", line 30, in load_gfpgan\n    upsampler = load_resrgan(ctx, bg_upscale)\n', "TypeError: load_resrgan() missing 1 re
quired positional argument: 'device'\n"]
```

**Comment by ssube** [comment]
Fixed the GFPGAN device error, but using Real ESRGAN with GFPGAN is still producing scattered tiles:

![image](https://user-images.githubusercontent.com/451959/216994080-928bff62-846a-4ffb-bf36-2a20c2092bcd.png)

![image](https://user-images.githubusercontent.com/451959/216994007-ec518787-a51e-4774-a6a2-dcfd0178fbb1.png)

**Comment by ssube** [comment]
Most of the app seems to be working, but there are a few issues around combined upscaling + correction and the outscale parameter that I want to fix before cutting the release.
