### ISSUE TITLE
v0.7.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#143]
Issues:

- #38 
- #62
- #78 
- #87 
- #90 
- #95 
- #103 
- #104 
- #107 
- #114 
- #115 
- #116 
- #117 
- #119 
- #120 
- #124 
- #130 
- #134 
- #135 
- #139 
- #140 
- #146
- #147 
- #148 
- #149 
- #150 

Merges:

- #118 
- #123 
- #126 
- #131 
- #133 
- #136 

Testing:

- txt2img
  - 256x256 with SD v1.5
    - [x] should fail: neon blobs
  - 512x512 with SD v1.5
    - DEIS Multi
      - [x] should work
    - DPM Multi
      - [x] should work
    - Euler A
      - [x] should work
  - 512x512 with SD v2.1
    - [x] should work
  - 768x768 with SD v2.1
    - [x] should work, given sufficient memory
  - extra models
    - 512x512 with Knollingcase
      - [x] should work
    - 512x512 with OpenJourney
      - [x] should work
    - 256x256 with OpenJourney
      - [x] should work
- img2img
  - 256x256 input
    - [x] should fail: neon blobs
  - 512x512 input
    - [x] should work
  - 1024x768 input
    - [x] should work
- inpaint
  - outpaint
    - 0 all sides
      - [x] should work, run 1 tile
    - 256 all sides
      - [x] should work, run 8 tiles
    - 512 top and bottom, 0 left and right
      - [x] should work, run 3 tiles
    - 512 left and right, 0 top and bottom
      - [x] should work, run 3 tiles
- upscale
  - Real ESRGAN
    - x4 with CodeFormer
      - [x] should work
    - x4 with GFPGAN
      - [x] should work
    - x4 without face correction
      - [x] should work
    - x2 model and x4 scale
      - ~should sort of work: ignores scale and uses x2~ fails now: `Target sizes: [1, 3, 2048, 2048].  Tensor sizes: [3, 1024, 1024]`
    - x4 model and x2 scale
      - [x] should fail: tiles
    - v3 model and x2 scale
      - ~should work~ fails: because the model was trained/exported at x4, it ignores the x2 scale/outscale and the image is cut off
    - v3 model and x4 scale
      - [x] should work
  - Stable Diffusion
    - using x2 scale
      - [x] should fail: tiles
    - using x4 scale
      - [x] should work
    - with CodeFormer
      - [x] should work
    - with GFPGAN
      - [x] should work
- interactions
  - generate a new image
    - [x] should request and then load an image from the server
  - delete a pending image
    - [x] should remove a single image and leave the rest
  - delete a finished image
    - [x] should remove a single image and leave the rest
  - copy an image to img2img
    - [x] should switch to the img2img tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to inpaint
    - [x] should switch to the inpaint tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to upscale
    - [x] should switch to the upscale tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy two images to blend
    - [x] should switch to the blend tab
    - [x] should populate the image sources
    - [x] the generate button should be enabled once both sources have been populated
  - persist on refresh
    - [x] loading images
    - [x] switching tabs

Release:

- [x] check and fix lint
- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make VERSION
- [x] make sure packages and images have been built
- [x] update GH pages bundle and default version
- [x] write release notes
- [x] post release on GH
- [ ] make follow up tickets
- [ ] close milestone and checklist

**Comment by ssube** [comment]
Testing discovered some bugs that need to be fixed before the release:

- https://github.com/ssube/onnx-web/issues/146
- https://github.com/ssube/onnx-web/issues/147
- https://github.com/ssube/onnx-web/issues/148
- https://github.com/ssube/onnx-web/issues/149
- post-multiply on inpaint causing ghosting: https://github.com/ssube/onnx-web/issues/150)

There are a few minor bugs that should be fixed in this release or the next:

- mask canvas does not immediately update when copying an image if one has already been copied

**Comment by ssube** [comment]
The second round of testing discovered two minor bugs in `should fail` cases that will not block the release:

- upscale, Real ESRGAN, x2 model and x4 scale
  - should sort of work: ignores scale and uses x2
  - fails now: `Target sizes: [1, 3, 2048, 2048].  Tensor sizes: [3, 1024, 1024]`
- v3 model and x2 scale
  - should work
  - fails: because the model was trained/exported at x4, it ignores the x2 scale/outscale and the image is cut off

Neither of this is supposed to work, but they should be addressed with validation or exporting v3 at x2.
