### ISSUE TITLE
v0.8.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#217]
Issues:

- #54 
- #113 
- #122 
- #127 
- #132 
- #138 
- #141 
- #144 
- #145 
- #151 
- #152 
- #155 
- #156 
- #157 
- #158 
- #160 
- #161 
- #166 
- #167 
- #170 
- #172 
- #179 
- #180 
- #181 
- #187 
- #188 
- #193 
- #194 
- #195 
- #221 
- #222 
- #224 
- #226 
- #228
- #229
- #233 
- #234

Merges:

- #45 
- #163 
- #169 
- #173 
- #174 
- #175 
- #176 
- #177 
- #178 
- #199 
- #200 
- #204 
- #205 
- #206 
- #208 
- #209 
- #214 
- #215 
- #218 
- #220 
- #223 

Testing:

- txt2img
  - 256x256 with SD v1.5
    - [x] ~should fail: neon blobs~ worked, but that's ok
    - [x] has automation
  - 512x512 with SD v1.5
    - DEIS Multi
      - [x] should work
    - DPM Multi
      - [x] should work
      - [x] has automation
    - Euler A
      - [x] should work
    - Heun
      - [x] should work
      - [x] has automation
  - 512x512 with SD v2.1
    - [x] should work
    - [x] has automation
  - 768x768 with SD v2.1
    - [x] should work, given sufficient memory
    - [x] has automation
  - extra models
    - 512x512 with Knollingcase
      - [x] should work
      - [x] has automation
    - 512x512 with OpenJourney
      - [x] should work
      - [x] has automation
    - 256x256 with OpenJourney
      - [x] should work
  - textual inversion
    - 512x512 with SD v1.5 + Autumn (embeddings)
      - [x] should work 
    - 512x512 with SD v1.5 + Minecraft (concept)
      - [x] should work 
- img2img
  - 256x256 input
    - [x] should work: expanded into valid image
    - [x] has automation
  - 512x512 input
    - [x] should work
    - [x] has automation
  - 1024x768 input
    - [x] should work
- inpaint
  - regular inpaint
    - black mask
      - [x] should keep all pixels, same image
      - [x] has automation
    - white mask
      - [x] should replace all pixels, different image
      - [x] has automation
  - outpaint
    - 0 all sides
      - [x] should work, run 1 tile
      - primarily a client-side test
    - 256 all sides
      - [x] should work, run 8 tiles
      - [x] has automation
    - 512 top and bottom, 0 left and right
      - [x] should work, run 3 tiles
      - [x] has automation
    - 512 left and right, 0 top and bottom
      - [x] should work, run 3 tiles
      - [x] has automation
- upscale
  - Real ESRGAN
    - x4 with CodeFormer
      - [x] should work
    - x4 with GFPGAN
      - [x] should work
    - x4 without face correction
      - [x] should work
      - [x] has automation
    - x2 without face correction
      - [x] should work
      - [x] has automation
    - x2 model and x4 scale
      - [x] should sort of work: ignores scale and uses x2
    - x4 model and x2 scale
      - [x] should fail: tiles
    - v3 model and x4 scale
      - [x] should work
  - Stable Diffusion
    - using x2 scale
      - [x] should fail: tiles
    - using x4 scale
      - [x] should work
    - with CodeFormer
      - [x] should work
    - with GFPGAN
      - [x] should work
    - without face correction
      - [x] should work
- blend
  - two 512x512 inputs
    - [x] should work
  - two 1024x1024 inputs
    - [x] should work
  - two different size inputs
    - 256x256 and 512x512
      - [x] should work
    - 512x512 and 1024x1024
      - [x] should work
- interactions
  - generate a new image
    - [x] should request and then load an image from the server
  - delete a pending image
    - [x] should remove a single image and leave the rest
  - delete a finished image
    - [x] should remove a single image and leave the rest
  - copy an image to img2img
    - [x] should switch to the img2img tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to inpaint
    - [x] should switch to the inpaint tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to upscale
    - [x] should switch to the upscale tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy two images to blend
    - [x] should switch to the blend tab
    - [x] should populate the image sources
    - [x] the generate button should be enabled once both sources have been populated
  - state should persist on refresh
    - [x] loading images
    - [x] switching tabs
    - [x] images sources do not
- schedulers
  - [x] DDIM
  - [x] DDPM
  - [x] DEIS Multi
  - [x] DPM Multi
  - [x] DPM Single
  - [x] Euler A
  - [x] Euler
  - [x] Heun
  - [ ] iPNDM
  - [x] KDPM2 A
  - [x] KDPM2
  - [ ] Karras Ve
  - [x] LMS
  - [x] PNDM
  - [x] UniPC Multi

Release:

- [x] fix any late arrival bugs
- [x] check on/add `UniPCMultistepScheduler`
- [x] document `ONNX_WEB_EXTRA_ARGS`
- [x] more bugs
- [x] update release tests to include Textual Inversions
- [x] check and fix lint
- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make VERSION
- [x] make sure packages and images have been built
- [x] update GH pages bundle and default version
- [x] post release on GH
- [x] make follow up tickets
- [x] close milestone and checklist

**Comment by ssube** [comment]
There are a few bugs around model conversion that still need to be fixed, as well as LoRA token expansion.

**Comment by ssube** [comment]
All of the bugs that have been reported so far have been fixed, and the release test script passed on my Win10 + AMD + DirectML and Ubuntu + Nvidia + CUDA systems. Unfortunately, my Ubuntu + AMD + ROCm test machine is not cooperating, so I need to fix that or will have to release without specifically testing ROCm, which I don't like very much.

The new `ONNX_WEB_EXTRA_ARGS` variable still needs to be documented and I need to check if the `UniPCMultistepScheduler` can be added yet.

**Comment by ssube** [comment]
- the Karras Ve scheduler is still broken (`TypeError: KarrasVeScheduler.step() missing 1 required positional argument: 'sample_hat'`)
- iPNDM is still producing chips (LMS and PNDM may as well without enough steps)
- the Generate button on the Blend tab is enabled even without the second source
