### ISSUE TITLE
v0.8.1 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#240]
Issues:

- #227

Merges:

- #239

Testing:

- release automation
  - [x] Windows 10 + AMD + DirectML
  - [x] Ubuntu 22.04 + Nvidia + CUDA

Release:

- [x] fix any late arrival bugs
- [x] check and fix lint
- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make VERSION
- [x] make sure packages and images have been built
- [x] update GH pages bundle and default version
- [x] post release on GH
- [x] make follow up tickets
- [x] close milestone and checklist
