### ISSUE TITLE
v0.10.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#368]
Issues:

- #153 
- #154
- #159 
- #165 
- #183 
- #184 
- #185 
- #207 
- #278 
- #279 
- #292 
- #293 
- #300 
- #301
- #302 
- #303 
- #305 
- #309 
- #312 
- #315 
- #316 
- #320 
- #323 
- #327 
- #328 
- #329 
- #330 
- #331 
- #336 
- #340 
- #342 
- #345 
- #348 
- #351 
- #354 
- #355 
- #356 
- #358 
- #360 
- #365 
- #366 
- #367 
- #369 
- #370 
- #371 
- #372 
- #373 
- #383
- #385 
- #387 

Merges:

- TODO

Testing:

- txt2img
  - 256x256 with SD v1.5
    - [ ] should work
    - [x] has automation
  - 512x512 with SD v1.5
    - DEIS Multi
      - [ ] should work
      - [x] has automation
    - DPM Multi
      - [ ] should work
      - [x] has automation
    - Euler A
      - [ ] should work
    - Heun
      - [ ] should work
      - [x] has automation
    - UniPC Multi
      - [ ] should work
      - [x] has automation
  - 512x512 with SD v2.1
    - [ ] should work
    - [x] has automation
  - 768x768 with SD v2.1
    - [ ] should work, given sufficient memory
    - [x] has automation
  - extra models
    - 512x512 with Knollingcase
      - [ ] should work
      - [x] has automation
    - 512x512 with OpenJourney
      - [ ] should work
      - [x] has automation
    - 256x256 with OpenJourney
      - [ ] should work
      - [x] has automation
  - textual inversion
    - 512x512 with SD v1.5 + Autumn (embeddings)
      - [ ] should work 
      - [x] has automation
    - 512x512 with SD v1.5 + Minecraft (concept)
      - [ ] should work 
      - [x] has automation
  - LoRA weights
    - 512x512 with SD v1.5 + Taters 
      - [ ] should work 
      - [x] has automation
- img2img
  - 256x256 input
    - [ ] should work: expanded into valid image
    - [x] has automation
  - 512x512 input
    - [ ] should work
    - [x] has automation
  - 1024x768 input
    - [ ] should work
    - [x] has automation
- inpaint
  - regular inpaint
    - black mask
      - [ ] should keep all pixels, same image
      - [x] has automation
    - white mask
      - [ ] should replace all pixels, different image
      - [x] has automation
  - outpaint
    - 0 all sides
      - [ ] should work, run 1 tile
      - primarily a client-side test
    - 256 all sides
      - [ ] should work, run 8 tiles
      - [x] has automation
    - 512 top and bottom, 0 left and right
      - [ ] should work, run 3 tiles
      - [x] has automation
    - 512 left and right, 0 top and bottom
      - [ ] should work, run 3 tiles
      - [x] has automation
- upscale
  - Real ESRGAN
    - x4 with CodeFormer
      - [ ] should work
      - [x] has automation
    - x4 with GFPGAN
      - [ ] should work
      - [x] has automation
    - x4 without face correction
      - [ ] should work
      - [x] has automation
    - x2 without face correction
      - [ ] should work
      - [x] has automation
    - x2 model and x4 scale
      - [ ] should sort of work: ignores scale and uses x2
    - x4 model and x2 scale
      - [ ] ~~should fail: tiles~~ worked, seemes to ignore scale
    - v3 model and x4 scale
      - [ ] should work
  - Stable Diffusion
    - using x2 scale
      - [ ] should fail: tiles
    - using x4 scale
      - [ ] should work
      - [x] has automation
    - with CodeFormer
      - [ ] should work
      - [x] has automation
    - with GFPGAN
      - [ ] should work
      - [x] has automation
- blend
  - two 512x512 inputs
    - [ ] should work
    - [x] has automation
  - two 1024x1024 inputs
    - [ ] should work
  - two different size inputs
    - 256x256 and 512x512
      - [ ] should work
    - 512x512 and 1024x1024
      - [ ] should work
- interactions
  - generate a new image
    - [ ] should request and then load an image from the server
  - delete a pending image
    - [ ] should remove a single image and leave the rest
  - delete a finished image
    - [ ] should remove a single image and leave the rest
  - copy an image to img2img
    - [ ] should switch to the img2img tab
    - [ ] should populate the image source
    - [ ] the generate button should be enabled
  - copy an image to inpaint
    - [ ] should switch to the inpaint tab
    - [ ] should populate the image source
    - [ ] the generate button should be enabled
  - copy an image to upscale
    - [ ] should switch to the upscale tab
    - [ ] should populate the image source
    - [ ] the generate button should be enabled
  - copy two images to blend
    - [ ] should switch to the blend tab
    - [ ] should populate the image sources
    - [ ] the generate button should be enabled once both sources have been populated
  - state should persist on refresh
    - [ ] loading images
    - [ ] switching tabs
    - [ ] images sources do not
- schedulers
  - [ ] DDIM
  - [ ] ~~DDPM~~ #190 
  - [ ] DEIS Multi
  - [ ] DPM Multi
  - [ ] DPM Single
  - [ ] Euler A
  - [ ] Euler
  - [ ] Heun
  - [ ] ~~iPNDM~~ #297
  - [ ] KDPM2 A
  - [ ] KDPM2
  - [ ] ~~Karras Ve~~ #189
  - [ ] LMS
  - [ ] PNDM
  - [ ] UniPC Multi
- providers
  - [ ] CUDA 11.7
  - [ ] CPU
  - [ ] DirectML
  - [ ] ROCm 5.4
- conversion
  - SD v1.5
    - [ ] fp32
    - [ ] onnx-fp16
    - [ ] torch-fp16
  - SD v2.1
    - [ ] fp32
    - [ ] ~~onnx-fp16~~ broken: https://github.com/ssube/onnx-web/issues/364
    - [ ] torch-fp16
  - SD upscaling
    - [ ] fp32
    - [ ] onnx-fp16 
    - [ ] torch-fp16

Release:

- [ ] update readme features
- [ ] update user guide
- [ ] update release tests
- [ ] fix any late arrival bugs
- [ ] check and fix lint
- [ ] update readme screenshot
- [ ] update package versions and stage files
- [ ] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make VERSION
- [ ] make sure packages and images have been built
  - [ ] build ROCm container
  - [ ] build Windows bundle
- [ ] update GH pages bundle and default version
- [ ] post release on GH
- [ ] make follow up tickets
- [ ] close milestone and checklist
