### ISSUE TITLE
v0.11.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#418]
Issues:

- #17 
- #129 
- #164 
- #189
- #190 
- #359 
- #376 
- #378 
- #379 
- #398
- #404
- #414
- #419 
- #420 
- #421
- #422
- #424 
- #425 
- #426 
- #427 
- #429 
- #431 
- #432
- #433 
- #436
- #437 
- #445 
- #446 

Merges:

- #406 
- #407 
- #408 
- #409 
- #411 
- #412 
- #415
- #417 
- #430 
- #434 
- #435 
- #443 
- #447 

Testing:

- txt2img
  - 256x256 with SD v1.5
    - [x] should work
    - [x] has automation
  - 512x512 with SD v1.5
    - DEIS Multi
      - [x] should work
      - [x] has automation
    - DPM Multi
      - [x] should work
      - [x] has automation
    - Euler A
      - [x] should work
    - Heun
      - [x] should work
      - [x] has automation
    - UniPC Multi
      - [x] should work
      - [x] has automation
  - 512x512 with SD v2.1
    - [x] should work
    - [x] has automation
  - 768x768 with SD v2.1
    - [x] should work, given sufficient memory
    - [x] has automation
  - 1024x1024 with SDXL
    - [x] should work, given sufficient memory
    - [x] has automation
  - 512x512 with SDXL Turbo
    - [x] should work, given sufficient memory
    - [x] has automation
  - extra models
    - 512x512 with Knollingcase
      - [x] should work
      - [x] has automation
    - 512x512 with OpenJourney
      - [x] should work
      - [x] has automation
    - 256x256 with OpenJourney
      - [x] should work
      - [x] has automation
  - textual inversion
    - 512x512 with SD v1.5 + Autumn (embeddings)
      - [x] should work 
      - [x] has automation
    - 512x512 with SD v1.5 + Minecraft (concept)
      - [x] should work 
      - [x] has automation
  - LoRA weights
    - 512x512 with SD v1.5 + Taters 
      - [x] should work 
      - [x] has automation
- img2img
  - 256x256 input
    - [x] should work: expanded into valid image
    - [x] has automation
  - 512x512 input
    - [x] should work
    - [x] has automation
  - 1024x768 input
    - [x] should work
    - [x] has automation
- inpaint
  - regular inpaint
    - black mask
      - [x] should keep all pixels, same image
      - [x] has automation
    - white mask
      - [x] should replace all pixels, different image
      - [x] has automation
  - outpaint
    - 0 all sides
      - [x] should work, run 1 tile
      - primarily a client-side test
    - 256 all sides
      - [x] should work, run 8 tiles
      - [x] has automation
    - 512 top and bottom, 0 left and right
      - [x] should work, run 3 tiles
      - [x] has automation
    - 512 left and right, 0 top and bottom
      - [x] should work, run 3 tiles
      - [x] has automation
- upscale
  - Real ESRGAN
    - x4 with CodeFormer
      - [x] should work
      - [x] has automation
    - x4 with GFPGAN
      - [x] should work
      - [x] has automation
    - x4 without face correction
      - [x] should work
      - [x] has automation
    - x2 without face correction
      - [x] should work
      - [x] has automation
    - x2 model and x4 scale
      - [x] should sort of work: ignores scale and uses x2
    - x4 model and x2 scale
      - [x] ~~should fail: tiles~~ worked, seemes to ignore scale
    - v3 model and x4 scale
      - [x] should work
  - Stable Diffusion
    - using x2 scale
      - [x] should fail: tiles
    - using x4 scale
      - [x] should work
      - [x] has automation
    - with CodeFormer
      - [x] should work
      - [x] has automation
    - with GFPGAN
      - [x] should work
      - [x] has automation
- blend
  - two 512x512 inputs
    - [x] should work
    - [x] has automation
  - two 1024x1024 inputs
    - [x] should work
  - two different size inputs
    - 256x256 and 512x512
      - [x] should work
    - 512x512 and 1024x1024
      - [x] should work
- interactions
  - generate a new image
    - [x] should request and then load an image from the server
  - delete a pending image
    - [x] should remove a single image and leave the rest
  - delete a finished image
    - [x] should remove a single image and leave the rest
  - copy an image to img2img
    - [x] should switch to the img2img tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to inpaint
    - [x] should switch to the inpaint tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to upscale
    - [x] should switch to the upscale tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy two images to blend
    - [x] should switch to the blend tab
    - [x] should populate the image sources
    - [x] the generate button should be enabled once both sources have been populated
  - state should persist on refresh
    - [x] loading images
    - [x] switching tabs
    - [x] images sources do not
- schedulers
  - [x] DDIM
  - [x] DDPM
  - [x] DEIS Multi
  - [x] DPM Multi
  - [x] DPM SDE (Turbo)
  - [x] DPM Single
  - [x] Euler
  - [x] Euler A
  - [x] Heun
  - [x] ~~iPNDM~~ #297
  - [x] KDPM2 A
  - [x] KDPM2
  - [x] LCM
  - [x] LMS
  - [x] PNDM
  - [x] UniPC Multi
- providers
  - [x] CUDA 11.7
  - [x] CPU
  - [x] DirectML
  - [x] ROCm 5.4
- conversion
  - SD v1.5
    - [x] fp32
    - [x] onnx-fp16
  - SD v2.1
    - [x] fp32
    - [x] ~~onnx-fp16~~ broken: https://github.com/ssube/onnx-web/issues/364
  - SD upscaling
    - [x] fp32
    - [x] onnx-fp16 
  - SDXL
    - [x] fp32
    - [x] onnx-fp16
  - custom VAE
    - [x] SD v1.5
    - [x] SDXL

Release:

- [x] update readme features
- [x] update user guide
- [x] update release tests
- [x] fix any late arrival bugs
- [x] check and fix lint
- [x] update readme screenshot
- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make VERSION
- [x] make sure packages and images have been built
  - [x] build ROCm container
  - [x] build Windows bundle
- [x] update GH pages bundle and default version
- [x] post release on GH
- [x] make follow up tickets
- [ ] close milestone and checklist
- post about it
  - [x] in Discord: https://discord.com/channels/1076986446516334622/1091195591096283146/1188597596814590134
  - [x] on Civitai: https://civitai.com/articles/3506/onnx-web-v0110-is-out-adding-support-for-sdxl-sdxl-turbo-lcm-and-more
  - [ ] on Reddit

**Comment by ssube** [comment]
The first RC for v0.11 has been built:

- Windows bundle: https://f349bba2d0da1e24be3a08642dead2d7.r2.cloudflarestorage.com/onnx-web-dist/onnx-web-v0.11.0-rc-0b31ad0a.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=040cfef0274b8d8a98aeca8f48dbf1ac%2F20231202%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231202T174016Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=83c89d514a90e8ec75baf93b5a7a1056247f15d0dd6998d8af9392699fda6aa3

**Comment by ssube** [comment]
Release tests are currently passing with `--mse 10.0`, which should be reduced before release.

New tests need to be added to the test plan for SDXL and LCM.

**Comment by ssube** [comment]
New release tests have been added, along with a getting started guide for new users. Most new features have been documented except for some parameters in the user guide.

Release tests are still passing at mse 10.0, although that can be reduced if you skip non-deterministic schedulers.

**Comment by bzlibby** [comment]
manual interactions QA:
- generating a new image
  - [x] requests and then loads a new image from the server 
- canceling a pending image
  - [x] removes the pending image and leaves the resst
- deleting a finished image
  - [x] removes the deleted image and leaves the rest
- copying a finished image to img2img
  - [x] switches to the img2img tab
  - [x] populates the image source with the correct image
  - [x] the generate button is enabled
- copy an image to inpaint
  - **switches to the inpaint tab, but then the page crashes**
  - related console error:
  - this does not happen when copying the image to inpaint while already on the inpaint tab
  ```
  main.js:36221 Uncaught Error: value not found
    at mustExist (main.js:36221:13)
    at getContext (main.js:76838:20)
    at getClearContext (main.js:76844:17)
    at MaskCanvas (main.js:76755:9)
    at renderWithHooks (main.js:14786:28)
    at mountIndeterminateComponent (main.js:17642:23)
    at beginWork (main.js:18658:24)
    at HTMLUnknownElement.callCallback (main.js:5821:24)
    at Object.invokeGuardedCallbackDev (main.js:5848:26)
    at invokeGuardedCallback (main.js:5882:41)
  ```
- copy an image to upscale
  - **switches to the upscale tab, but then the page crashes**
  - **the upscale tab in general crashes when manually navigating to it**
  - related console error (happens in both instances)
  ```
  Uncaught TypeError: Cannot read properties of undefined (reading 'matchAll')
    at extractNetworks (main.js:82363:33)
    at main.js:82277:24
    at mountMemo (main.js:15472:29)
    at Object.useMemo (main.js:15815:26)
    at useMemo (main.js:1179:31)
    at PromptTextBlock (main.js:82276:20)
    at renderWithHooks (main.js:14786:28)
    at mountIndeterminateComponent (main.js:17642:23)
    at beginWork (main.js:18658:24)
    at HTMLUnknownElement.callCallback (main.js:5821:24)
  ```
- copy two images to blend
  - **switches to the blend tab, but then the page crashes**
  - this does not happen when copying the images to blend while already on the blend tab
  - related console error:
  ```
  Uncaught Error: value not found
    at mustExist (main.js:36221:13)
    at getContext (main.js:76838:20)
    at getClearContext (main.js:76844:17)
    at MaskCanvas (main.js:76755:9)
    at renderWithHooks (main.js:14786:28)
    at mountIndeterminateComponent (main.js:17642:23)
    at beginWork (main.js:18658:24)
    at beginWork$1 (main.js:22635:24)
    at performUnitOfWork (main.js:22061:23)
    at workLoopSync (main.js:21994:15)
  ```
- states after refresh:
  - [x] loading images persist
  - [x] tab location persists
  - [x] image sources do not persist

**Comment by ssube** [comment]
Thank you for helping with the UI testing. I was able to reproduce 2 of those 3 bugs, but I was not able to find the crash on the upscale tab. I know where that is in the code and put some defensive checks in place, but I wasn't able to reproduce it, so I'm not able to verify that it is fixed. The `MaskCanvas` crash was easy to reproduce, so I'm pretty sure I was able to fix that one.

**Comment by ssube** [comment]
Most of the release tests have passed, but there are two remaining errors that I'm aware of:

- converting upscaling models using the Windows bundle fails with a deprecated import error
- running the SD v2.1 release tests against the Windows bundle fails with a tensor shape error while parsing the prompt

The first one will block the release until I can fix it, but the second might be related to the lack of negative prompt in the test data, and SD v2.1 is not enabled/converted by default.

I have gone through some of Civitai's most popular models and checked the licenses, and it looks like most of them allow redistribution under the same terms, so I will be preparing pre-converted archives for them. I may replace the Windows bundle's extras file with one that downloads the pre-converted archives to make things faster/easier for new users.

**Comment by ssube** [comment]
Both of the remaining errors have been resolved:

- the conversion error was fixed with a monkeypatch in basicsr to use the newer import
- the SD v2.1 and inpainting/outpainting test errors were caused by badly converted models, converted again resolved them

The latest RC bundle is https://pub-3c28d2c7c34e41c6a9189ffe0abd7d0b.r2.dev/onnx-web-v0.11.0-rc-3d245a66.zip.
