### ISSUE TITLE
v0.12.0 release checklist

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#458]
Issues:

- #438 
- #455
- #456
- #457

Merges:

- #450 
- #452 

Tests:

- [x] automated release tests
- [x] smoke test changed areas
  - [x] SDXL image output (noise)
  - [x] SDXL conversion
  - [x] ESRGAN conversion
  - [x] ESRGAN usage
  - [x] GFPGAN usage
  - [x] ControlNet parameters
- [x] smoke test web UI
  - generate a new image
    - [x] should request and then load an image from the server
  - delete a pending image
    - [x] should remove a single image and leave the rest
  - delete a finished image
    - [x] should remove a single image and leave the rest
  - copy an image to img2img
    - [x] should switch to the img2img tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to inpaint
    - [x] should switch to the inpaint tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy an image to upscale
    - [x] should switch to the upscale tab
    - [x] should populate the image source
    - [x] the generate button should be enabled
  - copy two images to blend
    - [x] should switch to the blend tab
    - [x] should populate the image sources
    - [x] the generate button should be enabled once both sources have been populated
  - state should persist on refresh
    - [x] loading images
    - [x] switching tabs
    - [x] images sources do not

Release:

- ~~update readme features~~
- [x] update user guide
- ~~update release tests~~
- [x] fix any late arrival bugs
- [x] check and fix lint
- ~~update readme screenshot~~
- [x] update package versions and stage files
- [x] run `commit-and-tag-version --sign --git-tag-fallback --commit-all --release-as=minor` to make v0.12.0
- [x] push everything: `GIT_ARGS=--follow-tags make git-push`
- [ ] make sure packages and images have been built
  - [ ] build ROCm container
  - [x] build Windows bundle
- [x] update GH pages bundle and default version
- [x] post release on GH
- [ ] make follow up tickets
- [ ] close milestone and checklist
